dependencies:
- name: elasticsearch
  version: 7.6.0
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: kibana
  version: 7.6.0
  repository: https://helm.elastic.co
  condition: kibana.enabled
- name: filebeat
  version: 4.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: filebeat.enabled
- name: logstash
  version: 2.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: logstash.enabled
- name: fluentd
  version: 2.3.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: fluentd.enabled
- name: fluent-bit
  version: 2.8.11
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: fluent-bit.enabled
- name: fluentd-elasticsearch
  version: 2.0.7
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: fluentd-elasticsearch.enabled
- name: nginx-ldapauth-proxy
  version: 0.1.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: nginx-ldapauth-proxy.enabled

- name: elasticsearch-curator
  version: 2.1.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch-curator.enabled
- name: elasticsearch-exporter
  version: 3.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch-exporter.enabled
