apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: sre-efk-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities: null
defaultAddCapabilities: 
  - IPC_LOCK
fsGroup:
  type: RunAsAny
groups:
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users: 
  - system:serviceaccount:sre-monitoring-logging:sre-efk-sa
volumes:
- '*'